<?php

/**
 * BaseClaimerDamageType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $type
 * @property string $name
 * @property string $tbl_name
 * @property boolean $has_coowners
 * @property boolean $has_documents
 * @property Doctrine_Collection $Damages
 * @property Doctrine_Collection $DocumentsTypes
 * 
 * @method string              getType()           Returns the current record's "type" value
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getTblName()        Returns the current record's "tbl_name" value
 * @method boolean             getHasCoowners()    Returns the current record's "has_coowners" value
 * @method boolean             getHasDocuments()   Returns the current record's "has_documents" value
 * @method Doctrine_Collection getDamages()        Returns the current record's "Damages" collection
 * @method Doctrine_Collection getDocumentsTypes() Returns the current record's "DocumentsTypes" collection
 * @method ClaimerDamageType   setType()           Sets the current record's "type" value
 * @method ClaimerDamageType   setName()           Sets the current record's "name" value
 * @method ClaimerDamageType   setTblName()        Sets the current record's "tbl_name" value
 * @method ClaimerDamageType   setHasCoowners()    Sets the current record's "has_coowners" value
 * @method ClaimerDamageType   setHasDocuments()   Sets the current record's "has_documents" value
 * @method ClaimerDamageType   setDamages()        Sets the current record's "Damages" collection
 * @method ClaimerDamageType   setDocumentsTypes() Sets the current record's "DocumentsTypes" collection
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaimerDamageType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('claimer_damage_type');
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tbl_name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('has_coowners', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('has_documents', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClaimerDamage as Damages', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $this->hasMany('ClaimerDocumentType as DocumentsTypes', array(
             'local' => 'id',
             'foreign' => 'damage_type_id'));
    }
}