<?php

/**
 * BaseClaimerBusiness
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $damage_id
 * @property string $business_kind
 * @property string $business_name
 * @property integer $business_value_before_turnover_id
 * @property integer $business_value_before_profit_id
 * @property integer $business_value_today_turnover_id
 * @property integer $business_value_today_profit_id
 * @property integer $business_value_before_id
 * @property integer $business_value_after_id
 * @property integer $business_value_total_id
 * @property integer $business_address_now_id
 * @property ClaimerDamage $Damage
 * @property ClaimerValue $ValueBT
 * @property ClaimerValue $ValueBP
 * @property ClaimerValue $ValueTT
 * @property ClaimerValue $ValueTP
 * @property ClaimerValue $ValueBefore
 * @property ClaimerValue $ValueAfter
 * @property ClaimerValue $ValueTotal
 * @property ClaimerAddress $AddressNow
 * 
 * @method integer         getDamageId()                          Returns the current record's "damage_id" value
 * @method string          getBusinessKind()                      Returns the current record's "business_kind" value
 * @method string          getBusinessName()                      Returns the current record's "business_name" value
 * @method integer         getBusinessValueBeforeTurnoverId()     Returns the current record's "business_value_before_turnover_id" value
 * @method integer         getBusinessValueBeforeProfitId()       Returns the current record's "business_value_before_profit_id" value
 * @method integer         getBusinessValueTodayTurnoverId()      Returns the current record's "business_value_today_turnover_id" value
 * @method integer         getBusinessValueTodayProfitId()        Returns the current record's "business_value_today_profit_id" value
 * @method integer         getBusinessValueBeforeId()             Returns the current record's "business_value_before_id" value
 * @method integer         getBusinessValueAfterId()              Returns the current record's "business_value_after_id" value
 * @method integer         getBusinessValueTotalId()              Returns the current record's "business_value_total_id" value
 * @method integer         getBusinessAddressNowId()              Returns the current record's "business_address_now_id" value
 * @method ClaimerDamage   getDamage()                            Returns the current record's "Damage" value
 * @method ClaimerValue    getValueBT()                           Returns the current record's "ValueBT" value
 * @method ClaimerValue    getValueBP()                           Returns the current record's "ValueBP" value
 * @method ClaimerValue    getValueTT()                           Returns the current record's "ValueTT" value
 * @method ClaimerValue    getValueTP()                           Returns the current record's "ValueTP" value
 * @method ClaimerValue    getValueBefore()                       Returns the current record's "ValueBefore" value
 * @method ClaimerValue    getValueAfter()                        Returns the current record's "ValueAfter" value
 * @method ClaimerValue    getValueTotal()                        Returns the current record's "ValueTotal" value
 * @method ClaimerAddress  getAddressNow()                        Returns the current record's "AddressNow" value
 * @method ClaimerBusiness setDamageId()                          Sets the current record's "damage_id" value
 * @method ClaimerBusiness setBusinessKind()                      Sets the current record's "business_kind" value
 * @method ClaimerBusiness setBusinessName()                      Sets the current record's "business_name" value
 * @method ClaimerBusiness setBusinessValueBeforeTurnoverId()     Sets the current record's "business_value_before_turnover_id" value
 * @method ClaimerBusiness setBusinessValueBeforeProfitId()       Sets the current record's "business_value_before_profit_id" value
 * @method ClaimerBusiness setBusinessValueTodayTurnoverId()      Sets the current record's "business_value_today_turnover_id" value
 * @method ClaimerBusiness setBusinessValueTodayProfitId()        Sets the current record's "business_value_today_profit_id" value
 * @method ClaimerBusiness setBusinessValueBeforeId()             Sets the current record's "business_value_before_id" value
 * @method ClaimerBusiness setBusinessValueAfterId()              Sets the current record's "business_value_after_id" value
 * @method ClaimerBusiness setBusinessValueTotalId()              Sets the current record's "business_value_total_id" value
 * @method ClaimerBusiness setBusinessAddressNowId()              Sets the current record's "business_address_now_id" value
 * @method ClaimerBusiness setDamage()                            Sets the current record's "Damage" value
 * @method ClaimerBusiness setValueBT()                           Sets the current record's "ValueBT" value
 * @method ClaimerBusiness setValueBP()                           Sets the current record's "ValueBP" value
 * @method ClaimerBusiness setValueTT()                           Sets the current record's "ValueTT" value
 * @method ClaimerBusiness setValueTP()                           Sets the current record's "ValueTP" value
 * @method ClaimerBusiness setValueBefore()                       Sets the current record's "ValueBefore" value
 * @method ClaimerBusiness setValueAfter()                        Sets the current record's "ValueAfter" value
 * @method ClaimerBusiness setValueTotal()                        Sets the current record's "ValueTotal" value
 * @method ClaimerBusiness setAddressNow()                        Sets the current record's "AddressNow" value
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaimerBusiness extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('claimer_business');
        $this->hasColumn('damage_id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             'notnull' => true,
             ));
        $this->hasColumn('business_kind', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('business_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('business_value_before_turnover_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('business_value_before_profit_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('business_value_today_turnover_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('business_value_today_profit_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('business_value_before_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('business_value_after_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('business_value_total_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('business_address_now_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaimerDamage as Damage', array(
             'local' => 'damage_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ClaimerValue as ValueBT', array(
             'local' => 'business_value_before_turnover_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('ClaimerValue as ValueBP', array(
             'local' => 'business_value_before_profit_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('ClaimerValue as ValueTT', array(
             'local' => 'business_value_today_turnover_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('ClaimerValue as ValueTP', array(
             'local' => 'business_value_today_profit_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('ClaimerValue as ValueBefore', array(
             'local' => 'business_value_before_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('ClaimerValue as ValueAfter', array(
             'local' => 'business_value_after_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('ClaimerValue as ValueTotal', array(
             'local' => 'business_value_total_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('ClaimerAddress as AddressNow', array(
             'local' => 'business_address_now_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));
    }
}