<?php

/**
 * BaseClaimerPerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $damage_id
 * @property string $person_name
 * @property string $person_firstname
 * @property integer $person_relationship_id
 * @property string $person_relationship_other
 * @property string $person_death_where
 * @property string $person_death_reason
 * @property integer $person_value_med_id
 * @property integer $person_value_funeral_id
 * @property integer $person_value_care_id
 * @property integer $person_value_work_id
 * @property ClaimerDamage $Damage
 * @property ClaimerPersonType $PersonType
 * @property ClaimerValue $ValueMed
 * @property ClaimerValue $ValueFuneral
 * @property ClaimerValue $ValueCare
 * @property ClaimerValue $ValueWork
 * 
 * @method integer           getDamageId()                  Returns the current record's "damage_id" value
 * @method string            getPersonName()                Returns the current record's "person_name" value
 * @method string            getPersonFirstname()           Returns the current record's "person_firstname" value
 * @method integer           getPersonRelationshipId()      Returns the current record's "person_relationship_id" value
 * @method string            getPersonRelationshipOther()   Returns the current record's "person_relationship_other" value
 * @method string            getPersonDeathWhere()          Returns the current record's "person_death_where" value
 * @method string            getPersonDeathReason()         Returns the current record's "person_death_reason" value
 * @method integer           getPersonValueMedId()          Returns the current record's "person_value_med_id" value
 * @method integer           getPersonValueFuneralId()      Returns the current record's "person_value_funeral_id" value
 * @method integer           getPersonValueCareId()         Returns the current record's "person_value_care_id" value
 * @method integer           getPersonValueWorkId()         Returns the current record's "person_value_work_id" value
 * @method ClaimerDamage     getDamage()                    Returns the current record's "Damage" value
 * @method ClaimerPersonType getPersonType()                Returns the current record's "PersonType" value
 * @method ClaimerValue      getValueMed()                  Returns the current record's "ValueMed" value
 * @method ClaimerValue      getValueFuneral()              Returns the current record's "ValueFuneral" value
 * @method ClaimerValue      getValueCare()                 Returns the current record's "ValueCare" value
 * @method ClaimerValue      getValueWork()                 Returns the current record's "ValueWork" value
 * @method ClaimerPerson     setDamageId()                  Sets the current record's "damage_id" value
 * @method ClaimerPerson     setPersonName()                Sets the current record's "person_name" value
 * @method ClaimerPerson     setPersonFirstname()           Sets the current record's "person_firstname" value
 * @method ClaimerPerson     setPersonRelationshipId()      Sets the current record's "person_relationship_id" value
 * @method ClaimerPerson     setPersonRelationshipOther()   Sets the current record's "person_relationship_other" value
 * @method ClaimerPerson     setPersonDeathWhere()          Sets the current record's "person_death_where" value
 * @method ClaimerPerson     setPersonDeathReason()         Sets the current record's "person_death_reason" value
 * @method ClaimerPerson     setPersonValueMedId()          Sets the current record's "person_value_med_id" value
 * @method ClaimerPerson     setPersonValueFuneralId()      Sets the current record's "person_value_funeral_id" value
 * @method ClaimerPerson     setPersonValueCareId()         Sets the current record's "person_value_care_id" value
 * @method ClaimerPerson     setPersonValueWorkId()         Sets the current record's "person_value_work_id" value
 * @method ClaimerPerson     setDamage()                    Sets the current record's "Damage" value
 * @method ClaimerPerson     setPersonType()                Sets the current record's "PersonType" value
 * @method ClaimerPerson     setValueMed()                  Sets the current record's "ValueMed" value
 * @method ClaimerPerson     setValueFuneral()              Sets the current record's "ValueFuneral" value
 * @method ClaimerPerson     setValueCare()                 Sets the current record's "ValueCare" value
 * @method ClaimerPerson     setValueWork()                 Sets the current record's "ValueWork" value
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaimerPerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('claimer_person');
        $this->hasColumn('damage_id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             'notnull' => true,
             ));
        $this->hasColumn('person_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('person_firstname', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('person_relationship_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('person_relationship_other', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('person_death_where', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('person_death_reason', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('person_value_med_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('person_value_funeral_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('person_value_care_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('person_value_work_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaimerDamage as Damage', array(
             'local' => 'damage_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ClaimerPersonType as PersonType', array(
             'local' => 'person_relationship_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('ClaimerValue as ValueMed', array(
             'local' => 'person_value_med_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('ClaimerValue as ValueFuneral', array(
             'local' => 'person_value_funeral_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('ClaimerValue as ValueCare', array(
             'local' => 'person_value_care_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('ClaimerValue as ValueWork', array(
             'local' => 'person_value_work_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));
    }
}