<?php

/**
 * BaseClaimerOtherloss
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $damage_id
 * @property integer $otherloss_value_between_id
 * @property integer $otherloss_value_peryear_id
 * @property integer $otherloss_years_until
 * @property ClaimerDamage $Damage
 * @property ClaimerValue $ValueBetween
 * @property ClaimerValue $ValuePerYear
 * 
 * @method integer          getDamageId()                   Returns the current record's "damage_id" value
 * @method integer          getOtherlossValueBetweenId()    Returns the current record's "otherloss_value_between_id" value
 * @method integer          getOtherlossValuePeryearId()    Returns the current record's "otherloss_value_peryear_id" value
 * @method integer          getOtherlossYearsUntil()        Returns the current record's "otherloss_years_until" value
 * @method ClaimerDamage    getDamage()                     Returns the current record's "Damage" value
 * @method ClaimerValue     getValueBetween()               Returns the current record's "ValueBetween" value
 * @method ClaimerValue     getValuePerYear()               Returns the current record's "ValuePerYear" value
 * @method ClaimerOtherloss setDamageId()                   Sets the current record's "damage_id" value
 * @method ClaimerOtherloss setOtherlossValueBetweenId()    Sets the current record's "otherloss_value_between_id" value
 * @method ClaimerOtherloss setOtherlossValuePeryearId()    Sets the current record's "otherloss_value_peryear_id" value
 * @method ClaimerOtherloss setOtherlossYearsUntil()        Sets the current record's "otherloss_years_until" value
 * @method ClaimerOtherloss setDamage()                     Sets the current record's "Damage" value
 * @method ClaimerOtherloss setValueBetween()               Sets the current record's "ValueBetween" value
 * @method ClaimerOtherloss setValuePerYear()               Sets the current record's "ValuePerYear" value
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaimerOtherloss extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('claimer_otherloss');
        $this->hasColumn('damage_id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             'notnull' => true,
             ));
        $this->hasColumn('otherloss_value_between_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('otherloss_value_peryear_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('otherloss_years_until', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaimerDamage as Damage', array(
             'local' => 'damage_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ClaimerValue as ValueBetween', array(
             'local' => 'otherloss_value_between_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('ClaimerValue as ValuePerYear', array(
             'local' => 'otherloss_value_peryear_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));
    }
}