<?php

/**
 * BaseClaimerMail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $subject
 * @property string $message
 * @property string $recipients_label
 * @property integer $sender_id
 * @property integer $manager_id
 * @property sfGuardUser $Sender
 * @property sfGuardUser $Manager
 * 
 * @method string      getSubject()          Returns the current record's "subject" value
 * @method string      getMessage()          Returns the current record's "message" value
 * @method string      getRecipientsLabel()  Returns the current record's "recipients_label" value
 * @method integer     getSenderId()         Returns the current record's "sender_id" value
 * @method integer     getManagerId()        Returns the current record's "manager_id" value
 * @method sfGuardUser getSender()           Returns the current record's "Sender" value
 * @method sfGuardUser getManager()          Returns the current record's "Manager" value
 * @method ClaimerMail setSubject()          Sets the current record's "subject" value
 * @method ClaimerMail setMessage()          Sets the current record's "message" value
 * @method ClaimerMail setRecipientsLabel()  Sets the current record's "recipients_label" value
 * @method ClaimerMail setSenderId()         Sets the current record's "sender_id" value
 * @method ClaimerMail setManagerId()        Sets the current record's "manager_id" value
 * @method ClaimerMail setSender()           Sets the current record's "Sender" value
 * @method ClaimerMail setManager()          Sets the current record's "Manager" value
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaimerMail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('claimer_mail');
        $this->hasColumn('subject', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('message', 'string', 10000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10000,
             ));
        $this->hasColumn('recipients_label', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sender_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('manager_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Sender', array(
             'local' => 'sender_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Manager', array(
             'local' => 'manager_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}