<?php

/**
 * BaseClaimerCattle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $damage_id
 * @property string $cattle_first_animal
 * @property string $cattle_first_eachyear
 * @property integer $cattle_first_loses
 * @property integer $cattle_first_value_id
 * @property string $cattle_second_animal
 * @property string $cattle_second_eachyear
 * @property integer $cattle_second_loses
 * @property integer $cattle_second_value_id
 * @property string $cattle_third_animal
 * @property string $cattle_third_eachyear
 * @property integer $cattle_third_loses
 * @property integer $cattle_third_value_id
 * @property string $cattle_fourth_animal
 * @property string $cattle_fourth_eachyear
 * @property integer $cattle_fourth_loses
 * @property integer $cattle_fourth_value_id
 * @property string $cattle_fifth_animal
 * @property string $cattle_fifth_eachyear
 * @property integer $cattle_fifth_loses
 * @property integer $cattle_fifth_value_id
 * @property string $cattle_ground_details
 * @property string $cattle_living_today
 * @property ClaimerDamage $Damage
 * @property ClaimerValue $ValueFirst
 * @property ClaimerValue $ValueSecond
 * @property ClaimerValue $ValueThird
 * @property ClaimerValue $ValueFourth
 * @property ClaimerValue $ValueFifth
 * 
 * @method integer       getDamageId()               Returns the current record's "damage_id" value
 * @method string        getCattleFirstAnimal()      Returns the current record's "cattle_first_animal" value
 * @method string        getCattleFirstEachyear()    Returns the current record's "cattle_first_eachyear" value
 * @method integer       getCattleFirstLoses()       Returns the current record's "cattle_first_loses" value
 * @method integer       getCattleFirstValueId()     Returns the current record's "cattle_first_value_id" value
 * @method string        getCattleSecondAnimal()     Returns the current record's "cattle_second_animal" value
 * @method string        getCattleSecondEachyear()   Returns the current record's "cattle_second_eachyear" value
 * @method integer       getCattleSecondLoses()      Returns the current record's "cattle_second_loses" value
 * @method integer       getCattleSecondValueId()    Returns the current record's "cattle_second_value_id" value
 * @method string        getCattleThirdAnimal()      Returns the current record's "cattle_third_animal" value
 * @method string        getCattleThirdEachyear()    Returns the current record's "cattle_third_eachyear" value
 * @method integer       getCattleThirdLoses()       Returns the current record's "cattle_third_loses" value
 * @method integer       getCattleThirdValueId()     Returns the current record's "cattle_third_value_id" value
 * @method string        getCattleFourthAnimal()     Returns the current record's "cattle_fourth_animal" value
 * @method string        getCattleFourthEachyear()   Returns the current record's "cattle_fourth_eachyear" value
 * @method integer       getCattleFourthLoses()      Returns the current record's "cattle_fourth_loses" value
 * @method integer       getCattleFourthValueId()    Returns the current record's "cattle_fourth_value_id" value
 * @method string        getCattleFifthAnimal()      Returns the current record's "cattle_fifth_animal" value
 * @method string        getCattleFifthEachyear()    Returns the current record's "cattle_fifth_eachyear" value
 * @method integer       getCattleFifthLoses()       Returns the current record's "cattle_fifth_loses" value
 * @method integer       getCattleFifthValueId()     Returns the current record's "cattle_fifth_value_id" value
 * @method string        getCattleGroundDetails()    Returns the current record's "cattle_ground_details" value
 * @method string        getCattleLivingToday()      Returns the current record's "cattle_living_today" value
 * @method ClaimerDamage getDamage()                 Returns the current record's "Damage" value
 * @method ClaimerValue  getValueFirst()             Returns the current record's "ValueFirst" value
 * @method ClaimerValue  getValueSecond()            Returns the current record's "ValueSecond" value
 * @method ClaimerValue  getValueThird()             Returns the current record's "ValueThird" value
 * @method ClaimerValue  getValueFourth()            Returns the current record's "ValueFourth" value
 * @method ClaimerValue  getValueFifth()             Returns the current record's "ValueFifth" value
 * @method ClaimerCattle setDamageId()               Sets the current record's "damage_id" value
 * @method ClaimerCattle setCattleFirstAnimal()      Sets the current record's "cattle_first_animal" value
 * @method ClaimerCattle setCattleFirstEachyear()    Sets the current record's "cattle_first_eachyear" value
 * @method ClaimerCattle setCattleFirstLoses()       Sets the current record's "cattle_first_loses" value
 * @method ClaimerCattle setCattleFirstValueId()     Sets the current record's "cattle_first_value_id" value
 * @method ClaimerCattle setCattleSecondAnimal()     Sets the current record's "cattle_second_animal" value
 * @method ClaimerCattle setCattleSecondEachyear()   Sets the current record's "cattle_second_eachyear" value
 * @method ClaimerCattle setCattleSecondLoses()      Sets the current record's "cattle_second_loses" value
 * @method ClaimerCattle setCattleSecondValueId()    Sets the current record's "cattle_second_value_id" value
 * @method ClaimerCattle setCattleThirdAnimal()      Sets the current record's "cattle_third_animal" value
 * @method ClaimerCattle setCattleThirdEachyear()    Sets the current record's "cattle_third_eachyear" value
 * @method ClaimerCattle setCattleThirdLoses()       Sets the current record's "cattle_third_loses" value
 * @method ClaimerCattle setCattleThirdValueId()     Sets the current record's "cattle_third_value_id" value
 * @method ClaimerCattle setCattleFourthAnimal()     Sets the current record's "cattle_fourth_animal" value
 * @method ClaimerCattle setCattleFourthEachyear()   Sets the current record's "cattle_fourth_eachyear" value
 * @method ClaimerCattle setCattleFourthLoses()      Sets the current record's "cattle_fourth_loses" value
 * @method ClaimerCattle setCattleFourthValueId()    Sets the current record's "cattle_fourth_value_id" value
 * @method ClaimerCattle setCattleFifthAnimal()      Sets the current record's "cattle_fifth_animal" value
 * @method ClaimerCattle setCattleFifthEachyear()    Sets the current record's "cattle_fifth_eachyear" value
 * @method ClaimerCattle setCattleFifthLoses()       Sets the current record's "cattle_fifth_loses" value
 * @method ClaimerCattle setCattleFifthValueId()     Sets the current record's "cattle_fifth_value_id" value
 * @method ClaimerCattle setCattleGroundDetails()    Sets the current record's "cattle_ground_details" value
 * @method ClaimerCattle setCattleLivingToday()      Sets the current record's "cattle_living_today" value
 * @method ClaimerCattle setDamage()                 Sets the current record's "Damage" value
 * @method ClaimerCattle setValueFirst()             Sets the current record's "ValueFirst" value
 * @method ClaimerCattle setValueSecond()            Sets the current record's "ValueSecond" value
 * @method ClaimerCattle setValueThird()             Sets the current record's "ValueThird" value
 * @method ClaimerCattle setValueFourth()            Sets the current record's "ValueFourth" value
 * @method ClaimerCattle setValueFifth()             Sets the current record's "ValueFifth" value
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaimerCattle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('claimer_cattle');
        $this->hasColumn('damage_id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             'notnull' => true,
             ));
        $this->hasColumn('cattle_first_animal', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cattle_first_eachyear', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cattle_first_loses', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('cattle_first_value_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('cattle_second_animal', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cattle_second_eachyear', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cattle_second_loses', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('cattle_second_value_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('cattle_third_animal', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cattle_third_eachyear', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cattle_third_loses', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('cattle_third_value_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('cattle_fourth_animal', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cattle_fourth_eachyear', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cattle_fourth_loses', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('cattle_fourth_value_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('cattle_fifth_animal', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cattle_fifth_eachyear', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cattle_fifth_loses', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('cattle_fifth_value_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('cattle_ground_details', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('cattle_living_today', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaimerDamage as Damage', array(
             'local' => 'damage_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ClaimerValue as ValueFirst', array(
             'local' => 'cattle_first_value_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('ClaimerValue as ValueSecond', array(
             'local' => 'cattle_second_value_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('ClaimerValue as ValueThird', array(
             'local' => 'cattle_third_value_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('ClaimerValue as ValueFourth', array(
             'local' => 'cattle_fourth_value_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('ClaimerValue as ValueFifth', array(
             'local' => 'cattle_fifth_value_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'cascade' => array(
             0 => 'delete',
             )));
    }
}