<?php

/**
 * BaseClaimerAddress
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $street
 * @property string $number
 * @property string $postbox
 * @property string $city
 * @property string $postcode
 * @property string $province
 * @property string $state
 * @property sfGuardUserProfile $sfGuardUserProfile
 * @property ClaimerDamage $ClaimerDamage
 * @property ClaimerBusiness $ClaimerBusiness
 * @property ClaimerCoowner $ClaimerCoowner
 * 
 * @method string             getStreet()             Returns the current record's "street" value
 * @method string             getNumber()             Returns the current record's "number" value
 * @method string             getPostbox()            Returns the current record's "postbox" value
 * @method string             getCity()               Returns the current record's "city" value
 * @method string             getPostcode()           Returns the current record's "postcode" value
 * @method string             getProvince()           Returns the current record's "province" value
 * @method string             getState()              Returns the current record's "state" value
 * @method sfGuardUserProfile getSfGuardUserProfile() Returns the current record's "sfGuardUserProfile" value
 * @method ClaimerDamage      getClaimerDamage()      Returns the current record's "ClaimerDamage" value
 * @method ClaimerBusiness    getClaimerBusiness()    Returns the current record's "ClaimerBusiness" value
 * @method ClaimerCoowner     getClaimerCoowner()     Returns the current record's "ClaimerCoowner" value
 * @method ClaimerAddress     setStreet()             Sets the current record's "street" value
 * @method ClaimerAddress     setNumber()             Sets the current record's "number" value
 * @method ClaimerAddress     setPostbox()            Sets the current record's "postbox" value
 * @method ClaimerAddress     setCity()               Sets the current record's "city" value
 * @method ClaimerAddress     setPostcode()           Sets the current record's "postcode" value
 * @method ClaimerAddress     setProvince()           Sets the current record's "province" value
 * @method ClaimerAddress     setState()              Sets the current record's "state" value
 * @method ClaimerAddress     setSfGuardUserProfile() Sets the current record's "sfGuardUserProfile" value
 * @method ClaimerAddress     setClaimerDamage()      Sets the current record's "ClaimerDamage" value
 * @method ClaimerAddress     setClaimerBusiness()    Sets the current record's "ClaimerBusiness" value
 * @method ClaimerAddress     setClaimerCoowner()     Sets the current record's "ClaimerCoowner" value
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaimerAddress extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('claimer_address');
        $this->hasColumn('street', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('number', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('postbox', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('postcode', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('province', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('state', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('city', array(
             'fields' => 'city',
             ));
        $this->index('postcode', array(
             'fields' => 'postcode',
             ));
        $this->index('state', array(
             'fields' => 'state',
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUserProfile', array(
             'local' => 'id',
             'foreign' => 'address_id'));

        $this->hasOne('ClaimerDamage', array(
             'local' => 'id',
             'foreign' => 'address_id'));

        $this->hasOne('ClaimerBusiness', array(
             'local' => 'id',
             'foreign' => 'business_address_now_id'));

        $this->hasOne('ClaimerCoowner', array(
             'local' => 'id',
             'foreign' => 'address_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}