<?php

/**
 * BaseClaimerCause
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $type
 * @property string $name
 * @property Doctrine_Collection $Damages
 * 
 * @method string              getType()    Returns the current record's "type" value
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getDamages() Returns the current record's "Damages" collection
 * @method ClaimerCause        setType()    Sets the current record's "type" value
 * @method ClaimerCause        setName()    Sets the current record's "name" value
 * @method ClaimerCause        setDamages() Sets the current record's "Damages" collection
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaimerCause extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('claimer_cause');
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClaimerDamage as Damages', array(
             'local' => 'id',
             'foreign' => 'cause_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}