<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sf_guard_user_id
 * @property string $email_alt
 * @property string $phone
 * @property string $phone_alt
 * @property integer $address_id
 * @property integer $manager_id
 * @property sfGuardUser $User
 * @property sfGuardUser $Manager
 * @property ClaimerAddress $Address
 * 
 * @method integer            getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method string             getEmailAlt()         Returns the current record's "email_alt" value
 * @method string             getPhone()            Returns the current record's "phone" value
 * @method string             getPhoneAlt()         Returns the current record's "phone_alt" value
 * @method integer            getAddressId()        Returns the current record's "address_id" value
 * @method integer            getManagerId()        Returns the current record's "manager_id" value
 * @method sfGuardUser        getUser()             Returns the current record's "User" value
 * @method sfGuardUser        getManager()          Returns the current record's "Manager" value
 * @method ClaimerAddress     getAddress()          Returns the current record's "Address" value
 * @method sfGuardUserProfile setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method sfGuardUserProfile setEmailAlt()         Sets the current record's "email_alt" value
 * @method sfGuardUserProfile setPhone()            Sets the current record's "phone" value
 * @method sfGuardUserProfile setPhoneAlt()         Sets the current record's "phone_alt" value
 * @method sfGuardUserProfile setAddressId()        Sets the current record's "address_id" value
 * @method sfGuardUserProfile setManagerId()        Sets the current record's "manager_id" value
 * @method sfGuardUserProfile setUser()             Sets the current record's "User" value
 * @method sfGuardUserProfile setManager()          Sets the current record's "Manager" value
 * @method sfGuardUserProfile setAddress()          Sets the current record's "Address" value
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             'notnull' => true,
             ));
        $this->hasColumn('email_alt', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone_alt', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('address_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('manager_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Manager', array(
             'local' => 'manager_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('ClaimerAddress as Address', array(
             'local' => 'address_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));
    }
}