<?php

/**
 * BaseClaimerRealestateType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $type
 * @property string $name
 * @property Doctrine_Collection $Realestates
 * 
 * @method string                getType()        Returns the current record's "type" value
 * @method string                getName()        Returns the current record's "name" value
 * @method Doctrine_Collection   getRealestates() Returns the current record's "Realestates" collection
 * @method ClaimerRealestateType setType()        Sets the current record's "type" value
 * @method ClaimerRealestateType setName()        Sets the current record's "name" value
 * @method ClaimerRealestateType setRealestates() Sets the current record's "Realestates" collection
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaimerRealestateType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('claimer_realestate_type');
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClaimerRealestate as Realestates', array(
             'local' => 'id',
             'foreign' => 'realestate_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}