<?php

/**
 * ClaimerCattle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ClaimerCattle extends BaseClaimerCattle
{
  public function postSave($event)
  {
    $damageValue = $this->calculateValue($this->getDamage()->getValue()->getCurrency()->getCode());
    
    $this->getDamage()->getValue()->setValue($damageValue);
    $this->getDamage()->getValue()->save();
  }
  
  protected function calculateValue($currency)
  {
    if (! is_numeric($this->getValueFirst()->getValue()) ||
        ! is_numeric($this->getValueSecond()->getValue()) ||
        ! is_numeric($this->getValueThird()->getValue()) ||
        ! is_numeric($this->getValueFourth()->getValue()) ||
        ! is_numeric($this->getValueFifth()->getValue()))
    {
      return 0;
    }
    
    return $this->getCattleFirstLoses() * $this->getValueFirst()->getCurrencyValue($currency)->getValue()
          + $this->getCattleSecondLoses() * $this->getValueSecond()->getCurrencyValue($currency)->getValue()
          + $this->getCattleThirdLoses() * $this->getValueThird()->getCurrencyValue($currency)->getValue()
          + $this->getCattleFourthLoses() * $this->getValueFourth()->getCurrencyValue($currency)->getValue()
          + $this->getCattleFifthLoses() * $this->getValueFifth()->getCurrencyValue($currency)->getValue();
  }
}
