<?php

/**
 * ClaimerMovableobjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerMovableobjectTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClaimerMovableobjectTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerMovableobject');
  }
}