<?php

/**
 * ClaimerCauseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerCauseTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClaimerCauseTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerCause');
  }
}