<?php

/**
 * ClaimerPerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ClaimerPerson extends BaseClaimerPerson
{
  public function preSave($event)
  {
    if ($this->getPersonType()->getType() != "other")
    {
      $this->setPersonRelationshipOther(null);
    }
  }
  
  public function postSave($event)
  {
    $damageValue = $this->calculateValue($this->getDamage()->getValue()->getCurrency()->getCode());
    
    $this->getDamage()->getValue()->setValue($damageValue);
    $this->getDamage()->getValue()->save();
  }
  
  protected function calculateValue($currency)
  {
    if (! is_numeric($this->getValueMed()->getValue()) ||
        ! is_numeric($this->getValueFuneral()->getValue()) ||
        ! is_numeric($this->getValueCare()->getValue()) ||
        ! is_numeric($this->getValueWork()->getValue()))
    {
      return 0;
    }
    
    return $this->getValueMed()->getCurrencyValue($currency)->getValue()
          + $this->getValueFuneral()->getCurrencyValue($currency)->getValue()
          + $this->getValueCare()->getCurrencyValue($currency)->getValue()
          + $this->getValueWork()->getCurrencyValue($currency)->getValue();
  }
}
