<?php

/**
 * ClaimerOtherlossTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerOtherlossTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClaimerOtherlossTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerOtherloss');
  }
}