<?php

/**
 * ClaimerDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerDocumentTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClaimerDocumentTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerDocument');
  }
  
  public function findByDamageAndType($damage_id, $type){      
    $q = $this->createQuery('c')
              ->where('c.damage_id = ?', $damage_id)
              ->andWhere('c.type_id = ?', $type);
  
    return $q->execute();
  }
  
  public function getDocumentForDamage(array $parameters)
  {
    $q = $this->createQuery('d')
              ->innerJoin('d.Damage r')
              ->where('MD5(d.filename) = ?', $parameters['md5_fname'])
              ->andWhere('r.validationcode = ?', $parameters['validationcode']);
    
    $results = $q->execute();
    
    return $results;
  }
}
