<?php

/**
 * ClaimerRateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerRateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaimerRateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaimerRate');
    }
    
    public function findRate($from, $to)
    {
      $q = $this->createQuery('r')
                ->innerJoin('r.CurrencyFrom f')
                ->innerJoin('r.CurrencyTo t')
                ->where('f.code = ?', $from)
                ->andWhere('t.code = ?', $to);
      
      return $q->fetchOne();
    }
}
