<?php

/**
 * ClaimerCurrencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerCurrencyTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClaimerCurrencyTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerCurrency');
  }

  public function getByCode($code = null)
  {
    if ($code === null)
    {
      $code = sfconfig::get('app_claimer_default_currency');
    }
    
    return Doctrine_Core::getTable('ClaimerCurrency')->findOneByCode($code);
  }
}
