<?php

/**
 * ClaimerRate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ClaimerRate extends BaseClaimerRate
{
  public function preSave($event)
  {
    if ($this->isNew())
    {
      if (! $this->relatedExists('CurrencyFrom'))
      {
        throw new sfException("Currency from must be defined.");
      }
      
      if (! $this->relatedExists('CurrencyTo'))
      {
        throw new sfException("Currency to must be defined.");
      }
    }
    
    $this->updateRate();
  }
  
  public function updateRate()
  {
    $today = new DateTime('now', new DateTimeZone(sfConfig::get('sf_default_timezone')));
    
    if ($this->isNew() || 
        $this->getDateTimeObject('updated_at')->diff($today)->days > 0 )
    {
      $rate = new sfRate(1, $this->getCurrencyFrom()->getCode(), $this->getCurrencyTo()->getCode());
      $rate = $rate->getRate();
      if (! $rate || ! is_numeric($rate))
      {
        throw new sfException(sprintf("The rate %s/%s could not be updated.", $this->getCurrencyFrom()->getCode(), $this->getCurrencyTo()->getCode()));
      }
      
      $this->setRate($rate);
      
      return true;
    }
    
    return false;
  }
}

