<?php

/**
 * ClaimerRealestateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerRealestateTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClaimerRealestateTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerRealestate');
  }
}