<?php

/**
 * ClaimerCoownerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerCoownerTable extends Doctrine_Table
{
  /**
  * Returns an instance of this class.
  *
  * @return object ClaimerCoownerTable
  */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerCoowner');
  }
  
  public function getMaxCoownercodeByDamage($damage_id)
  {
    $q = $this->createQuery('c')
      ->select('MAX(c.coownercode) as max_coownercode')
      ->where('c.damage_id = ?', $damage_id);
    
    $result = $q->fetchOne();
    
    return ($result->max_coownercode) ? $result->max_coownercode : 0;
  }
}
