<?php

/**
 * ClaimerPersonTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerPersonTypeTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClaimerPersonTypeTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerPersonType');
  }
}