<?php

/**
 * ClaimerCoowner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ClaimerCoowner extends BaseClaimerCoowner
{
  public function preSave($event)
  {
    if ($this->isNew())
    {
      if (! $this->relatedExists('Damage'))
      {
        throw new sfException("The damage must be defined.");
      }
      
      if (! isset($this->Address))
      {
        $address = new ClaimerAddress();
        $address->save();
        $this->setAddress($address);
      }
      
      $maxCoownercode = Doctrine_core::getTable('ClaimerCoowner')->getMaxCoownercodeByDamage($this->getDamage()->getId());
      
      $this->setCoownerCode($maxCoownercode + 1);
    }
  }
}
