<?php

/**
 * ClaimerHarvestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerHarvestTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClaimerHarvestTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerHarvest');
  }
}