<?php

/**
 * ClaimerValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ClaimerValue extends BaseClaimerValue
{
  public function preSave($event)
  {
    if (! $this->relatedExists('Currency'))
    {
      $this->setCurrencyByCode();
    }
  }
  
  public function setCurrencyByCode($code = null)
  {
    if (! $currency = Doctrine_Core::getTable('ClaimerCurrency')->getByCode($code))
    {
      throw new sfException(sprintf("The currency code %s does not exist.", $code));
    }
    
    $this->setCurrency($currency);
  }
  
  public function getDefaultCurrencyValue()
  {
    return $this->getCurrencyValue();
  }
  
  public function getCurrencyValue($code = null)
  {
    if (! $to = Doctrine_Core::getTable('ClaimerCurrency')->getByCode($code))
    {
      throw new sfException(sprintf("The currency code %s does not exist.", $code));
    }
    
    if ($this->getCurrency()->getCode() == $to->getCode())
    {
      return $this;
    }

    $value = new ClaimerValue();
    $value->setCurrency($to);
    $value->setValue($this->getRate($to->getCode()));
    
    return $value;
  }
  
  protected function getRate($to = null)
  {
    return $this->getValue() * $this->getCurrency()->getRate($to)->getRate();
  }
}
