<?php

/**
 * ClaimerRealestateTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerRealestateTypeTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClaimerRealestateTypeTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerRealestateType');
  }
}