<?php

/**
 * ClaimerValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerValueTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClaimerValueTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerValue');
  }
}
