<?php

/**
 * ClaimerBusinessTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerBusinessTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClaimerBusinessTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerBusiness');
  }
}