<?php

/**
 * ClaimerMailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerMailTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClaimerMailTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerMail');
  }

  public function getMailsQuery()
  {
    return $this->createQuery('m')
                ->leftJoin('m.Sender s');
  }
  
  public function getMailsBySenderIdQuery($senderId)
  {
    $q = $this->getMailsQuery()
              ->where('m.sender_id = ?', $senderId);

    return $q;
  }
}
