<?php

/**
 * ClaimerMail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ClaimerMail extends BaseClaimerMail
{
  protected $recipients = array();

  public function hasRecipients()
  {
    return ! empty($this->recipients);
  }
  
  public function getRecipients()
  {
    return $this->recipients;
  }
  
  public function setRecipients(Doctrine_Collection $recipients)
  {
    foreach ($recipients as $recipient)
    {
      if (! $recipient instanceof sfGuardUser)
      {
        throw new sfException("The recipient is not an user.");
      }
      
      if (! isset($recipient['email_address']) || empty($recipient['email_address']))
      {
        throw new sfException("The recipient does not have an email address.");
      }
      
      $this->recipients[] = $recipient['email_address'];
    }
  }
  
  public function isSentByUser(sfGuardUser $user)
  {
    return $this->getSender()->getId() == $user->getId();
  }
}
