<?php

/**
 * ClaimerCattleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerCattleTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClaimerCattleTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerCattle');
  }
}