<?php

/**
 * ClaimerAddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerAddressTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClaimerAddressTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerAddress');
  }
}