<?php

/**
 * ClaimerPersonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimerPersonTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClaimerPersonTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ClaimerPerson');
  }
}