<?php

/**
 * sfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    claimer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUserProfile extends BasesfGuardUserProfile
{
  public function preSave($event)
  {
    if (isset($this->User) && $this->getUser()->getEmailAddress() == $this->getEmailAlt())
    {
      $this->setEmailAlt(null);
    }

    if ($this->getPhone() == $this->getPhoneAlt())
    {
      $this->setPhoneAlt(null);
    }
  }
}
