# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .actions:
    error_404_module:       default
    error_404_action:       error404
    
    module_disabled_module: default
    module_disabled_action: disabled
    
    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure
  
  .settings:
    csrf_secret:            a_randomly_generated_secret
    
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS
    
    enabled_modules:        [sfGuardAuth, sfGuardForgotPassword]
    
    cache:                  true
    
    i18n:                   true
    default_culture:        en
    default_timezone:       Europe/Berlin
    
    standard_helpers:       [Partial, Cache, I18N, UrlActive]
