<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object sfGuardUserTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('sfGuardUser');
  }
  
  public function getUsersQuery()
  {
    return $this->createQuery('u')
                ->leftJoin('u.Profile p')
                ->leftJoin('p.Manager m');
  }
  
  public function getUsersInGroupsQuery($groups)
  {
    $q = $this->getUsersQuery()
              ->leftJoin('u.Groups g')
              ->whereIn('g.name', $groups);
    
    return $q;
  }
  
  public function getGrantedUsersInGroupsQuery($grants, $groups)
  {
    return $this->getUsersInGrantedGroupsQuery($grants)
                ->innerJoin('u.Groups g')
                ->whereIn('g.name', $groups);
  }
  
  public function getUsersInGrantedGroupsQuery($grants)
  {
    $groups = Doctrine_Core::getTable('sfGuardGroup')->getGroupsName();
    $groups = array_diff($groups, $grants);
    
    $q = $this->getUsersQuery();
    
    $subQuery = $q->createSubquery('uu')
                  ->from('sfGuardUser uu')
                  ->select('uu.id')
                  ->innerJoin('uu.Groups ug')
                  ->whereIn('ug.name', $grants);
    
    $subQuery2 = $q->createSubquery('uu2')
                  ->from('sfGuardUser uu2')
                  ->select('uu2.id')
                  ->innerJoin('uu2.Groups ug2')
                  ->whereIn('ug2.name', $groups);
    
    $q->where('u.id IN ('.$subQuery->getDql().')', $grants);
    $q->andWhere('u.id NOT IN ('.$subQuery2->getDql().')', $groups);
    
    return $q;
  }
  
  public function getUsersByManagerIdQuery($managerId)
  {
    $q = $this->getUsersQuery()
              ->select('u.*')
              ->addSelect('(SELECT SUM(v.value) FROM ClaimerDamage d LEFT JOIN d.Value v WHERE d.claimant_id = u.id GROUP BY u.id) as total_value')
              ->where('p.manager_id = ?', $managerId);
    
    return $q;
  }
}
