<h1>Legal conditions</h1>
<h2>Legal terms of usage for the registration on Claimer.org</h2>
<p><b>Only for climate damages / free of charge</b>: The registration on the server of Claimer.org is limited to damages which are due to climate change. The registration of climate change damages is free of any charge, whether it takes place for profit or not.</p>
<p><b>No exclusivity and right to delete</b>: You are free to register the same damages elsewhere. You have the right to delete your data on Claimer.org at any time.</p>
<p><b>No liability of Claimer.org for data loss</b>: Claimer.org has very limited resources and cannot guarantee full server reliablity, protection against hacking or data loss etc. Users recognise that they have no compensation right in case of any of these or similar cases.</p>
<p><b>Limitation of liability with regard to persons employed by Claimer.org</b>: The liablility of Claimer.org for actions of persons acting on behalf of Claimer.org is limited to cases of obvious lack of diligence of Claimer.org's direction with regard to the supervision of these persons. These persons are personally liable only in case of criminal actions.</p>
<p><b>No guarantee for litigation</b>: Claimer.org cannot guarantee that registrants' damages will be litigated. Claimer.org intends to inform registrants on future possibilities for litigation so that litigation is more likely to happen. Users can expect this to happen, but have no right for this service.</p>
<p><b>No lawyer-client relationship</b>: Registering damages on Claimer.org does not constitute a lawyer-client relationship with Claimer.org. Any communication between Claimer.org and users of the website does not constitute a legal counceling. Claimer.org is therefore not liable for damages caused by the use of such information.</p>
<p><b>Right to resiliate / obligation to update contact data</b>: Claimer.org has the right to resiliate its service subject to an email notification three months in advance. Users are in charge of keeping their contact data up-to-date and their mailbox accessible.</p>
<h2>Legal terms of usage for organizations or persons using our software on their own server</h2>
<p>By requesting the Claimer.org software for installation on your own server, you accept the following conditions:</p>
<p><b>Distinction between "Free license" and "Commercial license"</b>: The license is free of any charge if the software is used for the non-profit registration of environmental damages or for the profit or non-profit registration of climate damages. In all other cases the license is deemed to be commercial. Commercial licenses are subject to a written contract.</p>
<p><b>Mandatory link to Claimer.org</b>: The free license is subject to a condition. The following link to Claimer.org must be available on each individual page based on Claimer.org software and content: "Software and content provided by Claimer.org.". The lettering of the link must be at least 1 cm high and at least at the same size as the body text of the page.</p>
<p><b>Right to modify</b>: Users of the software have also the right to further develop the software for their own use which must be non-profit in the case of environmental damages other than climate damages.</p>
<p><b>No liability of Claimer.org</b>: Claimer.org will not accept any liability for software and content with regard to the free license. Claimer.org is not liable for the installation instructions either.</p>
<p><b>No right to further disseminate</b>: Legal or natural persons using the software are liable if they disseminate the software to third parties without the agreement of Claimer.org. They accept a contractual penalty twice as high as the damage caused to Claimer.org or the persons holding rights on behalf of Claimer.org.</p>
<p><b>Liability of users in case of abuse</b>: Any use going beyond the limits above or agreed in written form is subject to compensation. Compensation will be valued at 10 percent of the registered damage plus 10 Euro for each claimant, registered damage, uploaded document or registrar. The minimum damage is 10.000 Euro.</p>
<p><b>Agreement with hand-over</b>: Claimer.org is, for the time being, a project run by a citizens' initiative. It is intended to hand the project over to environmental or other organizations interested in climate compensation. When using the licenses mentioned above, you accept in advance that the contractual relationship might be transferred and that Claimer.org is liberated from its contractual obligations. The content of this license remains of course unchanged.</p>
<p><b>Applicable law and place of jurisdiction</b>: For any disputes in connection with the software and the content provided by Claimer.org, the law of Belgium/Brussels is applicable. Brussels is the place of jurisdiction. For its compensation rights, Claimer.org may choose the residence of the license user as place of jurisdiction.</p>
<p><b>Protection of persons acting for Claimer.org</b>: All clauses of this license protect equally the natural or legal persons holding rights or delivering services on behalf of Claimer.org. The liability of these natural or legal persons is, in addition, limited to 3000 Euro.</p>
<p><b>Limitation of liability with regard to persons employed by Claimer.org</b>: The liablility of Claimer.org for actions of persons acting on behalf of Claimer.org is limited to cases of obvious lack of diligence of Claimer.org's direction with regard to the supervision of these persons. Furthermore, the liability of Claimer.org is limited to 3000 Euro.</p>
<p><b>Partial invalidity of the terms</b>: Should any of these sentences or parts thereof be regarded as invalid, the remainder of the text keeps its validity.</p>
<p><b>Automatic replacement of an invalid clause</b>: The sentences regarded as invalid shall be automatically replaced by the sentence that is pursuing best the same purpose whilst still being acceptable under the applicable law.</p>
